# Generated by Django 3.2.4 on 2021-07-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210729_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
