# Generated by Django 3.2.4 on 2021-07-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this Product from view?'),
        ),
        migrations.AddField(
            model_name='product_line',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this Product Line (and all child Sub Product Lines and             Products) from view?'),
        ),
        migrations.AddField(
            model_name='sub_product_line',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this Sub Product Line (and all child Products) from             view?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Please enter a descriptive name for this Category.              Must be unique.', max_length=254, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Please enter a descriptive name for this Genre.              Must be unique.', max_length=254, unique=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_product_line',
            field=models.ForeignKey(help_text='Please assign this Product to a Sub Product Line.', on_delete=django.db.models.deletion.CASCADE, to='products.sub_product_line', verbose_name='Sub Product Line'),
        ),
        migrations.AlterField(
            model_name='product_line',
            name='name',
            field=models.CharField(help_text='Please enter a descriptive name for this Product Line.                  Must be unique.', max_length=254, unique=True, verbose_name='Product Line'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='Please enter a descriptive name for this Publisher.              Must be unique.', max_length=254, unique=True, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='reduced_reason',
            name='reason',
            field=models.CharField(help_text='Please enter a descriptive name for this Reduced Price Reason.                  Must be unique.', max_length=254, unique=True, verbose_name='Reduced Price Reason'),
        ),
        migrations.AlterField(
            model_name='stock_state',
            name='state',
            field=models.CharField(help_text='Please enter a descriptive name for this Stock State.              Must be unique.', max_length=254, unique=True, verbose_name='Stock State'),
        ),
    ]
