# Generated by Django 3.2.4 on 2021-06-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_line',
            name='description',
            field=models.TextField(default='Product Line Description'),
            preserve_default=False,
        ),
    ]
