# Generated by Django 3.2.4 on 2021-07-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210727_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Please enter a description for this Product.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product_line',
            name='description',
            field=models.TextField(blank=True, help_text='Please enter a description for this Product Line.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sub_product_line',
            name='description',
            field=models.TextField(blank=True, help_text='Please enter a description for this Sub Product Line', max_length=500, null=True),
        ),
    ]
