# Generated by Django 3.2.4 on 2021-06-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_line_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_product_line',
            name='description',
            field=models.TextField(default='Sub Product Line Description'),
            preserve_default=False,
        ),
    ]
